theme = "dracula"
client_id = "30ce1ea6950a4756b8c8eddde0587db3"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
  
 {status} 
 "{track}" 
 {artists} 
"""
playback_metadata_fields = [
    # "repeat",
    # "shuffle",
    # "volume",
    # "device",
]
notify_timeout_in_secs = 0
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = ""
pause_icon = ""
liked_icon = ""
border_type = "Rounded"
progress_bar_type = "Rectangle"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 0.5
enable_media_control = true
enable_streaming = "Always"
enable_notify = true
enable_cover_image_cache = true
default_device = "THREADRIPPER-DO"
notify_streaming_only = false
seek_duration_secs = 5
sort_artist_albums_by_type = false

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[layout]
playback_window_position = "Bottom"
playback_window_height = 6

[layout.library]
playlist_percent = 60
album_percent = 20

[device]
name = "THREADRIPPER-DO"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = true
normalization = false
autoplay = true

# Theme
playback_progress_bar = { bg = "BrightBlack", fg = "Red" }
