general {
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 150
    on-timeout = ~/.config/hypr/scripts/hypridle-dim
    on-resume = brightnessctl -r

    condition_cmd = ~/.config/hypr/scripts/audio-playing
    condition_retry = 30
}

listener {
    timeout = 330
    on-timeout = ~/.config/hypr/scripts/hypridle-dpms-off
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r

    condition_cmd = ~/.config/hypr/scripts/audio-playing
    condition_retry = 30
}

listener {
    timeout = 1800
    on-timeout = ~/.config/hypr/scripts/hypridle-suspend

    condition_cmd = ~/.config/hypr/scripts/audio-playing
    condition_retry = 30
}
